name: deploy-doc
on:
  push:
    tags:
      - doc**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.2
      - name: setup
        run: opam install . --deps-only --with-test --with-doc
      - name: build
        run: |
             opam exec -- ocaml ./configure.ml --sosa-zarith
             opam exec -- make doc
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _build/default/_doc/_html # The folder the action should deploy.
